### ISSUE TITLE
Wrong version info

### ISSUE THREAD

**Issue by IzzySoft** [1Gigabit/Andromix2#2]
Please fix versioning in your [`build.gradle`](https://github.com/1Gigabit/Andromix2/blob/1.0.2/app/build.gradle#L21). The tag linked to suggests this is the 3rd release you've made with the version 1.0.2 – yet `build.gradle` (and thus the APK) say it's the first release (`versionCode: 1`) and named `1.0` (`versionName`). Before that is done, [your RFP at F-Droid](https://gitlab.com/fdroid/rfp/-/issues/1935) cannot be processed.

Also remember to adjust them for future releases, or updates cannot be picked up by F-Droid. Even if they would, users would never receive update notifications, as Android goes by the `versionCode` to decide whether there are any updates; if that stays unchanged, the newer APK would simply be ignored.

And while I'm here: soon the issue bot will have your RFP scanned and complain about missing Fastlane structures. You can use my [Fastlane Cheat Sheet](https://gitlab.com/snippets/1895688) to get started with that; the minimum requirements, as outlined, are `short_description.txt` (the summary) and `full_description.txt` (the app description) for `en-US`, though it's strongly recommended to at least add some screenshots as well.

Thanks in advance!

**Comment by 1Gigabit** [comment]
Damn, nice eye for detail. Thank you so much, I've learned something new.

For phoneScreenshots I notice on your cheat sheet that it uses .png files. Am I able to use .jpg files instead?

**Comment by 1Gigabit** [comment]
nvm, just ended up converting to jpg using mogrify.

**Comment by IzzySoft** [comment]
Both PNG and JPG are fine for screenshots and, to my experience, also for the featureGraphic – but not always for the icon which then often does not show up.

Besides: if you replace the APK at the last tag, I can add it immediately to [my repo](https://apt.izzysoft.de/fdroid/repo) (currently the second largest) until it shows up at F-Droid. Just if you wish of course.

**Comment by 1Gigabit** [comment]
WIll upload new release

**Comment by IzzySoft** [comment]
Thanks a lot! The next sync of my repo will do the same. So in about 20h from now (around 7 pm UTC tomorrow) your app [will become available here](https://apt.izzysoft.de/fdroid/index/apk/com.hashmonopolist.andromix2). Be welcome using [my badges](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) if you want to link there e.g. from your Readme.

**Comment by 1Gigabit** [comment]
I pushed him a repository that icon before 20 hours would it update on your
repository

**Comment by IzzySoft** [comment]
It would update together with the next release. But with my repo, I can update it manually if you let me know when it's there. I just checked but didn't see it. As for F-Droid.org, it must be available at the same tag the app is build from, so you'd need to re-tag or create a new tag (or simply have it updated with the next version).
